# Generated by Django 4.2 on 2023-05-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_entrega_aprendiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='usuarios',
        ),
    ]
